export const departments: string[] = [
  'All departments',
  'Arts & Crafts',
  'Automotive',
  'Baby',
  'Beauty & Personal Care',
  'Books',
  'Computers',
  'Digital Music',
  'Electronics',
  'Kindle Store',
  'Prime Video',
  "Women's Fashion",
  "Men's Fashion",
  "Girls' Fashion",
  "Boys' Fashion",
  'Deals',
  'Health & Household',
  'Home & Kitchen',
  'Industrial & Scientific',
  'Luggage',
  'Movies & TV',
  "Music, CD's & Vinyl",
  'Pet Supplies',
  'Software',
  'Sports & Outdoors',
  'Tools & Home Improvement',
  'Toys & Games',
  'Video Games',
];
